spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  flyway:
    baseline-on-migrate: true
#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.ws: DEBUG
#server:
#  hostname: localhost
#  port: ${PORT:8080}
#mail:
#  server:
#    host: smtp.gmail.com
#    port: 587
#    username: polozov.test@gmail.com
#    password: ${hidden.email.password}

#
#    url: jdbc:${DATABASE_PATH}
#    username: ${DATABASE_USER}
#    password: ${DATABASE_PASSWORD}