create table admin (id integer not null auto_increment, admin_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table bots (id bigint not null auto_increment, gender varchar(255), is_active bit not null, password varchar(255), phone varchar(255), worker_id integer, primary key (id)) engine=InnoDB;;
create table bots_reviews (bots_id bigint not null, review_id bigint not null) engine=InnoDB;
create table categories (id bigint not null auto_increment, category_title varchar(255), primary key (id)) engine=InnoDB;
create table company (id bigint not null auto_increment, email varchar(255), is_active bit, link varchar(255), name varchar(255), number_phone varchar(255), category_id bigint, worker_id integer, primary key (id)) engine=InnoDB;
create table manager (id integer not null auto_increment, manager_name varchar(255) not null, admin_id integer, primary key (id)) engine=InnoDB;
create table review_base (id bigint not null auto_increment, text_review varchar(255), category bigint, primary key (id)) engine=InnoDB;
create table reviews (id bigint not null auto_increment, checked bit default false, create_date datetime, modificate_date datetime, payed bit default false, public_date datetime, text_review varchar(255), category_id bigint, company_id bigint, primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, activate_code varchar(255), archive bit not null, email varchar(255) not null, password varchar(255) not null, phone_number varchar(255) not null, role varchar(255), user_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table worker (id integer not null auto_increment, worker_name varchar(255) not null, manager_id integer, primary key (id)) engine=InnoDB;
alter table user drop index UK_ob8kqyqqgmefl0aco34akdtpe;
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email);
alter table user drop index UK_4bgmpi98dylab6qdvf9xyaxu4;
alter table user add constraint UK_4bgmpi98dylab6qdvf9xyaxu4 unique (phone_number);
alter table bots add constraint FKt59ob9xhqi74rfw4krcd6cd5w foreign key (worker_id) references worker (id);
alter table bots_reviews add constraint FKpoppc966g3iejskhbia8ugpak foreign key (review_id) references reviews (id);
alter table bots_reviews add constraint FKm74vkmtxkxbvd8gk42onry97y foreign key (bots_id) references bots (id);
alter table company add constraint FKht3vlqtsq2u55a52n96twbk68 foreign key (category_id) references categories (id);
alter table company add constraint FKnayrxrug21rrhfnrtwyjrbj9w foreign key (worker_id) references worker (id);
alter table manager add constraint FKk32qe1qwpdvedrn489nfhppkx foreign key (admin_id) references admin (id);
alter table review_base add constraint FK8xgy59lmmrwmdhm7lem7ismno foreign key (category) references categories (id);
alter table reviews add constraint FKh65wmfin3w5qrxnhm67q226qr foreign key (category_id) references categories (id);
alter table reviews add constraint FKifjxj1qfah58p4m25vly3ky8g foreign key (company_id) references company (id);
alter table worker add constraint FKmyruwd6v2yxqtwsi4hjsjuw0l foreign key (manager_id) references manager (id);